services:
  gestion_api:
    container_name: r401_gestion_api
    image: anguspllg/r401_gestion_api
    env_file:
      - .env
    ports:
      - '8202:80'
    environment:
      - PRODUCTION=true
      - BASE_AUTH_API_URL=https://auth-r401.paillaugue.fr
      - MYSQL_HOST=db_gestion
    depends_on:
      - db_gestion

  auth_api:
    container_name: r401_auth_api
    image: anguspllg/r401_auth_api
    env_file:
      - .env
    environment:
      - PRODUCTION=true
      - MYSQL_HOST=db_auth
    ports:
      - '8201:80'
    depends_on:
      - db_auth

  frontend:
    container_name: r401_frontend
    image: anguspllg/r401_frontend
    ports:
      - '8200:80'

  db_auth:
    image: mysql:latest
    restart: always
    container_name: r401_db_auth
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    env_file:
      - .env
    volumes:
      - ./mysql_data_auth:/var/lib/mysql
      - ./sql/auth.sql:/docker-entrypoint-initdb.d/init.sql

  db_gestion:
    image: mysql:latest
    restart: always
    container_name: r401_db_gestion
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./mysql_data_gestion:/var/lib/mysql
      - ./sql/gestion.sql:/docker-entrypoint-initdb.d/init.sql

  swagger-ui:
    ports:
      - 8203:8080
    image: swaggerapi/swagger-ui
    restart: always
    volumes:
      - ./swagger:/usr/share/nginx/html/api
    environment:
      URLS: "[{ url: \"./api/auth.yaml\", name: \"Auth\" },\
            { url: \"./api/gestion.yaml\", name: \"Gestion\" },
            ]"
