openapi: 3.0.3
info:
  title: R4.01-Project
  version: 1.0.0
servers:
  - url: https://auth-r401.paillaugue.fr
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /:
    post:
      tags:
        - Auth
      summary: Generate JWT
      description: Generate JWT authenicaton token to use for the other routes and the gestion API.
      operationId: generateJwt
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                  example: PASSWORD
                username:
                  type: string
                  example: USERNAME
            example:
              password: PASSWORD
              username: USERNAME
      responses:
        '200':
          description: 'User authenticated successfully'
        '400':
          description: 'Bad request - missing required fields - invalid credentials'
    get:
      tags:
        - Auth
      security:
        - bearerAuth: []
      summary: Get user data
      description: Get user data
      operationId: getUserData
      responses:
        '200':
          description: 'User authenticated successfully'
        '401':
          description: 'Unauthorized'

tags:
  - name: Auth
