FROM php:8.2-apache

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl

RUN docker-php-ext-install pdo pdo_mysql

COPY --from=composer:2 /usr/bin/composer /usr/bin/composer

COPY composer.json composer.lock ./

RUN composer install --no-dev --no-scripts --optimize-autoloader

COPY . /var/www/html
# Remove the api folder from the frontend image
RUN rm -rf /var/www/html/app/api

RUN sed -i 's|/var/www/html|/var/www/html/app|' /etc/apache2/sites-available/000-default.conf
RUN sed -i 's|/var/www/html|/var/www/html/app|' /etc/apache2/apache2.conf

EXPOSE 80

CMD ["apache2-foreground"]
