FROM php:8.2-apache

WORKDIR /var/www/html

RUN apt-get update && apt-get install -y \
    unzip \
    git \
    curl

RUN docker-php-ext-install pdo pdo_mysql

COPY ./app/api/auth ./api/auth
COPY ./app/lib ./lib
COPY ./app/modele ./modele

RUN sed -i 's|/var/www/html|/var/www/html/app/api/auth|' /etc/apache2/sites-available/000-default.conf
RUN sed -i 's|/var/www/html|/var/www/html/app/api/auth|' /etc/apache2/apache2.conf

EXPOSE 80

CMD ["apache2-foreground"]
