SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";
CREATE DATABASE IF NOT EXISTS `R401_projet_auth`;
USE `R401_projet_auth`;

DROP USER IF EXISTS 'R401_projet_auth' @'%';
CREATE USER 'R401_projet_auth' @'%' IDENTIFIED BY 'R401_projet_auth';
GRANT SELECT, INSERT, UPDATE, DELETE ON R401_projet_auth.* TO 'R401_projet_auth' @'%';

FLUSH PRIVILEGES;

CREATE TABLE user (
  id INT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(50) UNIQUE NOT NULL,
  password_hash VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `user` VALUES (1, 'Angus', '$2y$10$gaTtHQ9lwY8SEuayUhIW5.SIMqGeV2AaSAZZZPlWAk/HF7NAp7Nkm');
